Insert transport on purchase
NMF-earth/carbon-footprint pull request #20
Opened 2020-11-01 00:22 UTC by marlonemmerich

2020-11-01 07:59 UTC, PierreBresson requested changes
This data is for `transport.ts` not `purchase.ts`. Out of scope.

2020-11-02 18:42 UTC, marlonemmerich commented
Oh, i'm sorry!
Please, can you check if it's OK now?
Thanks!

2020-11-02 20:11 UTC, PierreBresson approved these changes

2020-11-02 20:11 UTC, PierreBresson commented
@marlonemmerich thank you 🤗

2020-11-02 20:11 UTC, merged